- name: Deploy
  hosts: all
  become: yes
  vars:
    working_dir: /home/ubuntu/code
  environment:
    CIRCLE_CI: ":master"
    DJANGO_SECRET_KEY: "{{ lookup('env','DJANGO_SECRET_KEY') }}"
    POSTGRES_HOST: "{{ lookup('env','POSTGRES_HOST') }}"
    POSTGRES_PORT: "{{ lookup('env','POSTGRES_PORT') }}"
    POSTGRES_DB: "{{ lookup('env','POSTGRES_DB') }}"
    POSTGRES_USER: "{{ lookup('env','POSTGRES_USER') }}"
    POSTGRES_PASSWORD: "{{ lookup('env','POSTGRES_PASSWORD') }}"
  tasks:

    - name: Pull Code
      git:
        repo: https://github.com/ahmed1293/aajm_list.git
        dest: "{{ working_dir }}"
        clone: no
        version: master

    - name: Log into DockerHub
      docker_login:
        username: "{{ lookup('env','DOCKER_USER') }}"
        password: "{{ lookup('env','DOCKER_PASS') }}"

    - name: Stop Containers
      shell: docker-compose stop
      args:
        chdir: "{{ working_dir }}"

    - name: Pull Images
      shell: docker-compose pull
      args:
        chdir: "{{ working_dir }}"

    - name: Start Containers
      shell: docker-compose up -d
      args:
        chdir: "{{ working_dir }}"

#    - assert:
#        that:
#          - "code_django_1.state.running"
#          - "code_postgres_1.state.running"


