- name: Deploy
  hosts: all
  become: yes
  vars:
    working_dir: /home/ubuntu/code
  environment:
    CIRCLE_CI: ":master"
    DOCKER_REGISTRY: "{{ lookup('env','DOCKER_REGISTRY') }}"
    DJANGO_SECRET_KEY: "{{ lookup('env','DJANGO_SECRET_KEY') }}"
    POSTGRES_HOST: "{{ lookup('env','POSTGRES_HOST') }}"
    POSTGRES_PORT: "{{ lookup('env','POSTGRES_PORT') }}"
    POSTGRES_DB: "{{ lookup('env','POSTGRES_DB') }}"
    POSTGRES_USER: "{{ lookup('env','POSTGRES_USER') }}"
    POSTGRES_PASSWORD: "{{ lookup('env','POSTGRES_PASSWORD') }}"

  tasks:

    - name: Pull Code
      git:
        repo: https://github.com/ahmed1293/aajm_list.git
        dest: "{{ working_dir }}"
        clone: no
        version: master

    - name: Log into DockerHub
      docker_login:
        username: "{{ lookup('env','DOCKER_USER') }}"
        password: "{{ lookup('env','DOCKER_PASS') }}"

    - name: Stop Containers
      docker_compose:
        project_src: "{{ working_dir }}"
        state: absent

    - name: Pull Images
      docker_compose:
        project_src: "{{ working_dir }}"
        pull: yes
        state: absent

    - name: Start Containers
      docker_compose:
        project_src: "{{ working_dir }}"
        state: present

    - name: Run Migrations
      shell: docker-compose run --rm django python manage.py migrate
      args:
        chdir: "{{ working_dir }}"

    - name: Collect Static Files
      shell: docker-compose exec django python manage.py collectstatic --noinput
      args:
        chdir: "{{ working_dir }}"

    - assert:
        that:
          - "django.code_django_1.state.running"
          - "postgres.code_postgres_1.state.running"


