- hosts: all
  become: yes
  tasks:

    - name: Update apt packages
      apt:
        upgrade: yes

    - name: Install make
      apt:
        name: make

    - name: Install Docker prerequisites
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent' ,'software-properties-common']

    - name: Import Docker's GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Install Docker CE
      apt:
        name: docker-ce

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.23.1/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
        dest: /usr/local/bin/docker-compose
        mode: +x
