version: '3'

services:
  postgres:
    image: postgres:10.4
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./.envs/postgres

  django:
    build:
      context: .
      dockerfile: compose/django/Dockerfile
    command: python manage.py runserver_plus 0.0.0.0:8000
    env_file:
      - ./.envs/postgres
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  node:
    build:
      context: .
      dockerfile: compose/node/Dockerfile
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules

volumes:
  pgdata: