version: '3.2'

services:

  postgres:
    image: ${DOCKER_REGISTRY}postgres${CI_BRANCH}
    build:
      context: .
      dockerfile: compose/postgres/Dockerfile
      cache_from:
        - ${DOCKER_REGISTRY}postgres${CI_BRANCH}
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  django:
    image: ${DOCKER_REGISTRY}django${CI_BRANCH}
    build:
      context: .
      dockerfile: compose/django/Dockerfile
      cache_from:
        - ${DOCKER_REGISTRY}django${CI_BRANCH}
    command: python manage.py runserver_plus 0.0.0.0:8000
    restart: always
    working_dir: /code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DJANGO_SECRET_KEY
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

volumes:
  pgdata: