# adds containers/settings needed in the pipeline (should be overridden by docker-compose.prod)
version: '3.2'

services:

  node:
    image: ${DOCKER_REGISTRY}node${CI_BRANCH}
    build:
      context: .
      dockerfile: compose/node/Dockerfile
      cache_from:
        - ${DOCKER_REGISTRY}node${CI_BRANCH}
    volumes:
      - .:/app/
      - /app/node_modules

  django:
    volumes:
      - .:/code

volumes:
  pgdata: