version: '3.2'

services:

  postgres:
    image: ${DOCKER_REGISTRY}postgres${CI_BRANCH}
    build:
      context: .
      dockerfile: compose/postgres/Dockerfile
      cache_from:
        - ${DOCKER_REGISTRY}postgres${CI_BRANCH}
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  django:
    image: ${DOCKER_REGISTRY}django${CI_BRANCH}
    build:
      context: .
      dockerfile: compose/django/Dockerfile
      cache_from:
        - ${DOCKER_REGISTRY}django${CI_BRANCH}
    volumes:
      - .:/code # this should only be necessary locally and on the CI (jest coverage wont work otherwise)
    command: gunicorn aajm_list.wsgi:application --bind 0.0.0.0:8000
    restart: always
    working_dir: /code
    expose:
      - "8000"
    depends_on:
      - postgres
    environment:
      - DJANGO_SECRET_KEY
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  nginx:
    image: ${DOCKER_REGISTRY}nginx${CI_BRANCH}
    build:
      context: .
      dockerfile: compose/nginx/production/Dockerfile
      cache_from:
        - ${DOCKER_REGISTRY}nginx${CI_BRANCH}
    ports:
      - "80:80"
    volumes:
      - ./staticfiles:/home/app/django/staticfiles
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - django

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

volumes:
  pgdata:
