version: '3'

services:
  postgres:
    image: ${DOCKER_REGISTRY}postgres:${CIRCLE_BRANCH}
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
      cache_from:
        - ${DOCKER_REGISTRY}postgres:${CIRCLE_BRANCH}
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./.envs/postgres
  django:
    image: ${DOCKER_REGISTRY}django:${CIRCLE_BRANCH}
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
      cache_from:
        - ${DOCKER_REGISTRY}django:${CIRCLE_BRANCH}
    command: python manage.py runserver_plus 0.0.0.0:8000
    env_file:
      - ./.envs/postgres
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  pgdata: